version: 0.0
os: linux
files:
  - source: ./html
    destination: webhost/webagencyads

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 900
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
